# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-19 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('tel', models.CharField(max_length=11, null=True, verbose_name='手机号')),
            ],
        ),
    ]
