# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-28 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('tel', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('sign', models.CharField(max_length=50, null=True, verbose_name='个人签名')),
                ('info', models.CharField(max_length=150, null=True, verbose_name='个人描述')),
                ('avatar', models.ImageField(null=True, upload_to='avatar/')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
